owner: dioptra-io 
repo: iris-uptime

sites:
  - name: Iris Website
    url: https://iris.dioptra.io
  - name: Iris Production API
    url: https://api.iris.dioptra.io/status
  - name: Iris Development API
    url: https://api.dev.iris.dioptra.io/status

assignees: 
  - iprsbot

status-website:
  baseUrl: /iris-uptime
  theme: night
  name: Iris Uptime
  introMessage: Monitoring page for the uptime of the [Iris system](https://iris.dioptra.io).
